services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-very-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-backend.onrender.com
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.jmdimazofdgdyjelfskj
      - key: DB_PASSWORD
        value: 3qtUvT7rFkxB_L$
      - key: DB_HOST
        value: aws-0-ap-south-1.pooler.supabase.com
      - key: DB_PORT
        value: 6543
